### ISSUE TITLE
AttributeError: '_Data' object has no attribute 'shape'

### ISSUE THREAD

**Issue by scls19fr** [TabViewer/gtabview#29]
Hello,

With Ubuntu 17.10 and Blaze version 0.10.1 I get the following error:

```
$ bin/gtabview 'mysql+mysqlconnector://root:password@localhost:3306/sample_db'
/usr/local/lib/python2.7/dist-packages/odo/backends/pandas.py:94: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
  @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
/usr/local/lib/python2.7/dist-packages/blaze/server/server.py:17: ExtDeprecationWarning: Importing flask.ext.cors is deprecated, use flask_cors instead.
  from flask.ext.cors import cross_origin
Traceback (most recent call last):
  File "bin/gtabview", line 102, in <module>
    sys.exit(main())
  File "bin/gtabview", line 94, in main
    transpose=args.transpose, metavar=args.filename)
  File "/home/scls/.local/lib/python2.7/site-packages/gtabview/__init__.py", line 169, in view
    transpose=transpose)
  File "/home/scls/.local/lib/python2.7/site-packages/gtabview/dataio.py", line 139, in read_model
    return as_model(data, hdr_rows=hdr_rows, idx_cols=idx_cols, transpose=transpose)
  File "/home/scls/.local/lib/python2.7/site-packages/gtabview/models.py", line 266, in as_model
    elif hasattr(data, '__array__') and len(data.shape) >= 2:
  File "/usr/local/lib/python2.7/dist-packages/blaze/expr/expressions.py", line 222, in __getattr__
    result = object.__getattribute__(self, key)
AttributeError: '_Data' object has no attribute 'shape'
```

**Comment by wavexx** [comment]
On Sun, Nov 19 2017, scls19fr wrote:
> AttributeError: '_Data' object has no attribute 'shape'

Indeed, there are some API changes in the newer Blaze versions.
Similarly, gtabview csv://xyz also fails.

I'll have a look.

**Comment by wavexx** [comment]
Looks like Blaze/Odo are completely broken right now. I cannot get them to work with python 3.8+, and looking at the upstream repository it seems that they're also now unmaintained. I get a lot of deprecation warnings running even basic stuff, but even just odo fails to read from a csv now.

I'm going to begrudgingly remove support for blaze entirely, since it was broken anyway.

**Comment by scls19fr** [comment]
https://github.com/blaze/blaze/issues/1669 and https://github.com/ibis-project/ibis/issues/2294#issuecomment-663053479 may be worth to have a look

**Comment by wavexx** [comment]
Closing this, but I'm looking for an alternative.

I was reading that just prior.. none of the alternatives seem to really match what blaze+odo was doing overall. Intake has been suggested in some other places, have you ever used it?

**Comment by scls19fr** [comment]
No sorry I never used neither [ibis](https://ibis-project.org/) nor [intake](https://intake.readthedocs.io/)
